### ISSUE TITLE
Administration delet

### ISSUE THREAD

**Issue by Nournagham** [projectestac/moodle-langpacks#4]
https://github.com/projectestac/moodle-langpacks/blob/fde1d03bf77ea287841e08da337a580cc59d00ff/ar/admin.php#L436

**Comment by toniginard** [comment]
Hi @Nournagham,

I don't understand what is your issue. If there is any error in any string, please report it in Moodle AMOS: https://lang.moodle.org/

This repository only contains a selection of strings exported from Moodle AMOS. Our recommendation is to use official Moodle translations.


Best wishes,
