### ISSUE TITLE
Informe d'errades de la traducció

### ISSUE THREAD

**Issue by jordimas** [projectestac/moodle-langpacks#5]
Ep!

Des de https://www.softcatala.org/recursos/memories/ baixem molts projectes lliures i els indexem per poder cercar les traduccions.

També generem informes d'errors de qualitat: Aquí podreu veure el del Moodle: https://static.softcatala.org/quality/moodle.html

Actualment generem aquests informes a partir de les traduccions que baixem de _-b MOODLE_40_STABLE git://git.moodle.org/moodle-langpacks.git_. Si aquest dipòsit (https://github.com/projectestac/moodle-langpacks/) és era la font de les traduccions en català, fem el canvi d'on baixar-les.

**Comment by toniginard** [comment]
Hola, Jordi,

Aquest repositori conté un subconjunt de les traduccions oficials del Moodle. En lloc de baixar-nos les traduccions completes dels idiomes que volem incorporar a la nostra plataforma, agafem només les traduccions dels components que tenim instal·lats. Cada vegada que preparem una versió nova, actualitzem les traduccions del servidor del Moodle, així que les traduccions que trobareu aquí no estan al dia.

Les versions oficials les trobareu en aquest URL, on heu de canviar $moodleversion i $lang pels valors corresponents:
https://download.moodle.org/download.php/direct/langpack/$moodleversion/$lang.zip.

En el cas de la versió 4.1 del català (la que fem servir ara), l'URL queda així:
https://packaging.moodle.org/langpack/4.1/ca.zip

Només heu de descomprimir l'arxiu i trobareu totes les traduccions disponibles per a la versió que trieu. Conté les traduccions del nucli del Moodle i, també, la de molts connectors i temes addicionals que nosaltres no agafem.


Salutacions,

Toni Ginard

**Comment by jordimas** [comment]
Gràcies!
